#!/bin/bash
#SBATCH --job-name=pyk2-contact-anal
#SBATCH --time=0-12:00:00
##SBATCH --mail-type=begin,end,fail,requeue
#SBATCH --output=temp/slurm-%A_%a.out
#SBATCH --export=all
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --mem=131072
#SBATCH --array=1,3,5

name=`echo "pyk2-cpd1-amber pyk2-cpd10-amber pyk2-cpd2-amber pyk2-cpd6-amber pyk2-cpd8-amber" | awk -v i=$SLURM_ARRAY_TASK_ID '{print $i}'`
./get-transition-state3.py $name 70 #1.0
