#!/bin/bash

name=$1
nanchor=$2
for i in `seq 1 143`
do
	#find the maximum energy along each pathway
	#energy=`tail -n$nanchor sample-pathways/$name-pathway-$i.out | sort -n -k5 | tail -n1 | awk '{print $5}'`
	energy=`head -n61 sample-pathways-energy/$name-pathway-$i | sort -n -k5 | tail -n1 | awk '{print $5}'`
	echo $i $energy
done
